# print(abs(-23.66))
# x = "ttsts"
# print(all(x))
# list = [23,34,23,11]
# print(all(list))
# n = 5
# print(all(n))
x = 3
# print(bin(x))
# print(bool(x))
# print(bytearray(x))
# print(bytes(x))
list = [23,43,23,54,34,45,33,23,33,23]
word = "Hello_world"
# print(len(list))
# print(max(list))
# print(min(list))
# print(len(word))
# # print(max(word))
# print(min(word))
# print(pow(x,2))
# print(reversed(word))
# print(reversed(list))
# print(sorted(list))
# print(sorted(word))
# print(sum(list))
# print(tuple(list))
# print(tuple(word))
# list.append(33)
# print(list)
# print(list.count(23))
# list2 = (20,37,37)
# list.extend(list2)
# print(list)
# print(list.index(33))
# list.insert(0,99)
# print(list)
# list.pop()
# print(list)
